### ISSUE TITLE
version for QGIS 2.0

### ISSUE THREAD

**Issue by luseework** [tsw-apropos/qmarxan#1]
I am using currently QGIS 2.2.0 but would like to use QMarxan which is currently only for older versions available. will there be a new version in the near future?

Thanks 

lucia

**Comment by aproposinfosystems** [comment]
Yes. I plan to release a new version of QMarxan for QGIS 2.x by September 2014. 

TSW

**Comment by aproposinfosystems** [comment]
The release of QMarxan for QGIS 2.x will now be in October 2014.

**Comment by alesarrett** [comment]
Is there any update on this issue? What is it needed to speed up the process? Code help? Financial support? Let us know...

**Comment by genFaille** [comment]
I'm really interested in knowing when that new compatible Qmarxan will be release? I was using Qmarxan last year and found it really usefull. And now i just found out that I can't use it with the new qgis 2.6. Thanks..

**Comment by alesarrett** [comment]
Now QGIS is already at version 2.8
I also strongly support this request.
Is there anything that can be done to help the new release of the plugin
for the version 2.x?
Thanks,

Ale
Il 25/feb/2015 21:19 "genFaille" notifications@github.com ha scritto:

**Comment by aproposinfosystems** [comment]
Thanks for your interesting. QMarxan for the QGIS 2.x branch is getting close to release. I've completely re-engineered it which took some time but the end result is that it is much faster for a variety of operations. I will probably release it as experimental sometime in March and help with testing will definitely be needed. I will also need help with documentation.

**Comment by aproposinfosystems** [comment]
QMarxanZ has replaced this and is now released as an experimental plugin for QGIS 2.8
